// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: ttb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{1}
}

func (x *UserId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TicketPurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To          string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	UserId      int32  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DiscoutCode string `protobuf:"bytes,5,opt,name=discout_code,json=discoutCode,proto3" json:"discout_code,omitempty"`
}

func (x *TicketPurchaseRequest) Reset() {
	*x = TicketPurchaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketPurchaseRequest) ProtoMessage() {}

func (x *TicketPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketPurchaseRequest.ProtoReflect.Descriptor instead.
func (*TicketPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{2}
}

func (x *TicketPurchaseRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TicketPurchaseRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TicketPurchaseRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TicketPurchaseRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketPurchaseRequest) GetDiscoutCode() string {
	if x != nil {
		return x.DiscoutCode
	}
	return ""
}

type TicketPurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Section string `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	SeatNum int32  `protobuf:"varint,3,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
}

func (x *TicketPurchaseResponse) Reset() {
	*x = TicketPurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketPurchaseResponse) ProtoMessage() {}

func (x *TicketPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketPurchaseResponse.ProtoReflect.Descriptor instead.
func (*TicketPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{3}
}

func (x *TicketPurchaseResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketPurchaseResponse) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *TicketPurchaseResponse) GetSeatNum() int32 {
	if x != nil {
		return x.SeatNum
	}
	return 0
}

type TicketDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Section string       `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	SeatNum int32        `protobuf:"varint,3,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
	From    string       `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To      string       `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Price   int32        `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	User    *UserRequest `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *TicketDetailsResponse) Reset() {
	*x = TicketDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetailsResponse) ProtoMessage() {}

func (x *TicketDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetailsResponse.ProtoReflect.Descriptor instead.
func (*TicketDetailsResponse) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{4}
}

func (x *TicketDetailsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketDetailsResponse) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *TicketDetailsResponse) GetSeatNum() int32 {
	if x != nil {
		return x.SeatNum
	}
	return 0
}

func (x *TicketDetailsResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TicketDetailsResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TicketDetailsResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketDetailsResponse) GetUser() *UserRequest {
	if x != nil {
		return x.User
	}
	return nil
}

type ModifySeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrTicketId int32  `protobuf:"varint,1,opt,name=curr_ticket_id,json=currTicketId,proto3" json:"curr_ticket_id,omitempty"`
	NewSeatNum   int32  `protobuf:"varint,2,opt,name=new_seat_num,json=newSeatNum,proto3" json:"new_seat_num,omitempty"`
	NewSection   string `protobuf:"bytes,3,opt,name=new_section,json=newSection,proto3" json:"new_section,omitempty"`
	UserId       int32  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ModifySeatRequest) Reset() {
	*x = ModifySeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySeatRequest) ProtoMessage() {}

func (x *ModifySeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySeatRequest.ProtoReflect.Descriptor instead.
func (*ModifySeatRequest) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{5}
}

func (x *ModifySeatRequest) GetCurrTicketId() int32 {
	if x != nil {
		return x.CurrTicketId
	}
	return 0
}

func (x *ModifySeatRequest) GetNewSeatNum() int32 {
	if x != nil {
		return x.NewSeatNum
	}
	return 0
}

func (x *ModifySeatRequest) GetNewSection() string {
	if x != nil {
		return x.NewSection
	}
	return ""
}

func (x *ModifySeatRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Section struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section string `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
}

func (x *Section) Reset() {
	*x = Section{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{6}
}

func (x *Section) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatNum   int32        `protobuf:"varint,1,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
	User      *UserRequest `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Available string       `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *Seat) Reset() {
	*x = Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{7}
}

func (x *Seat) GetSeatNum() int32 {
	if x != nil {
		return x.SeatNum
	}
	return 0
}

func (x *Seat) GetUser() *UserRequest {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Seat) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

type BookedSeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatNum int32  `protobuf:"varint,1,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
	Section string `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
}

func (x *BookedSeat) Reset() {
	*x = BookedSeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookedSeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookedSeat) ProtoMessage() {}

func (x *BookedSeat) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookedSeat.ProtoReflect.Descriptor instead.
func (*BookedSeat) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{8}
}

func (x *BookedSeat) GetSeatNum() int32 {
	if x != nil {
		return x.SeatNum
	}
	return 0
}

func (x *BookedSeat) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type SeatAllocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seats []*Seat `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
}

func (x *SeatAllocationResponse) Reset() {
	*x = SeatAllocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ttb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatAllocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatAllocationResponse) ProtoMessage() {}

func (x *SeatAllocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ttb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatAllocationResponse.ProtoReflect.Descriptor instead.
func (*SeatAllocationResponse) Descriptor() ([]byte, []int) {
	return file_ttb_proto_rawDescGZIP(), []int{9}
}

func (x *SeatAllocationResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

var File_ttb_proto protoreflect.FileDescriptor

var file_ttb_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x74, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x74, 0x62,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x18,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x74,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x5d, 0x0a, 0x16, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x73, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0xbc, 0x01, 0x0a, 0x15, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x74, 0x74, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x95, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x63, 0x75, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x61,
	0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x53, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x23,
	0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x41, 0x0a, 0x0a, 0x42, 0x6f,
	0x6f, 0x6b, 0x65, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x61, 0x74,
	0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a,
	0x16, 0x53, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x32, 0xba, 0x03, 0x0a, 0x0d, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x0c, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x74, 0x74, 0x62,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x74,
	0x74, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x0e, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x74, 0x74,
	0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0b, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x1a, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x53, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x53, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x74,
	0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0b, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x53, 0x65, 0x61, 0x74, 0x12, 0x0f, 0x2e, 0x74, 0x74, 0x62, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x53, 0x65, 0x61, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x41, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x61, 0x74,
	0x12, 0x16, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x74, 0x62, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x79, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2d,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x74, 0x62, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ttb_proto_rawDescOnce sync.Once
	file_ttb_proto_rawDescData = file_ttb_proto_rawDesc
)

func file_ttb_proto_rawDescGZIP() []byte {
	file_ttb_proto_rawDescOnce.Do(func() {
		file_ttb_proto_rawDescData = protoimpl.X.CompressGZIP(file_ttb_proto_rawDescData)
	})
	return file_ttb_proto_rawDescData
}

var file_ttb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ttb_proto_goTypes = []interface{}{
	(*UserRequest)(nil),            // 0: ttb.UserRequest
	(*UserId)(nil),                 // 1: ttb.UserId
	(*TicketPurchaseRequest)(nil),  // 2: ttb.TicketPurchaseRequest
	(*TicketPurchaseResponse)(nil), // 3: ttb.TicketPurchaseResponse
	(*TicketDetailsResponse)(nil),  // 4: ttb.TicketDetailsResponse
	(*ModifySeatRequest)(nil),      // 5: ttb.ModifySeatRequest
	(*Section)(nil),                // 6: ttb.Section
	(*Seat)(nil),                   // 7: ttb.Seat
	(*BookedSeat)(nil),             // 8: ttb.BookedSeat
	(*SeatAllocationResponse)(nil), // 9: ttb.SeatAllocationResponse
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_ttb_proto_depIdxs = []int32{
	0,  // 0: ttb.TicketDetailsResponse.user:type_name -> ttb.UserRequest
	0,  // 1: ttb.Seat.user:type_name -> ttb.UserRequest
	7,  // 2: ttb.SeatAllocationResponse.seats:type_name -> ttb.Seat
	0,  // 3: ttb.TicketBooking.RegisterUser:input_type -> ttb.UserRequest
	2,  // 4: ttb.TicketBooking.PurchaseTicket:input_type -> ttb.TicketPurchaseRequest
	1,  // 5: ttb.TicketBooking.GetTicketDetails:input_type -> ttb.UserId
	6,  // 6: ttb.TicketBooking.ViewSeatAllocation:input_type -> ttb.Section
	1,  // 7: ttb.TicketBooking.RemoveUser:input_type -> ttb.UserId
	8,  // 8: ttb.TicketBooking.RemoveUserBySeat:input_type -> ttb.BookedSeat
	5,  // 9: ttb.TicketBooking.ModifySeat:input_type -> ttb.ModifySeatRequest
	1,  // 10: ttb.TicketBooking.RegisterUser:output_type -> ttb.UserId
	3,  // 11: ttb.TicketBooking.PurchaseTicket:output_type -> ttb.TicketPurchaseResponse
	4,  // 12: ttb.TicketBooking.GetTicketDetails:output_type -> ttb.TicketDetailsResponse
	9,  // 13: ttb.TicketBooking.ViewSeatAllocation:output_type -> ttb.SeatAllocationResponse
	10, // 14: ttb.TicketBooking.RemoveUser:output_type -> google.protobuf.Empty
	10, // 15: ttb.TicketBooking.RemoveUserBySeat:output_type -> google.protobuf.Empty
	3,  // 16: ttb.TicketBooking.ModifySeat:output_type -> ttb.TicketPurchaseResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ttb_proto_init() }
func file_ttb_proto_init() {
	if File_ttb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ttb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketPurchaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketPurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Section); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookedSeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ttb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatAllocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ttb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ttb_proto_goTypes,
		DependencyIndexes: file_ttb_proto_depIdxs,
		MessageInfos:      file_ttb_proto_msgTypes,
	}.Build()
	File_ttb_proto = out.File
	file_ttb_proto_rawDesc = nil
	file_ttb_proto_goTypes = nil
	file_ttb_proto_depIdxs = nil
}
